### ISSUE TITLE
Intermittent: undefined method `this' for Gem::Specification

### ISSUE THREAD

**Issue by meringu** [zl4bv/aws-session-credentials#11]
Sometimes when I try to assume a role I get this.

```
$ aws-session assume-role --role-alias myrole
/usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0x8ea4cc aws-session-credentials-1.0.1> (NoMethodError)
        from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
        from /usr/local/rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
        from /usr/local/rvm/gems/ruby-2.3.1/gems/aws-session-credentials-1.0.1/exe/aws-session:2:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.3.1/bin/aws-session:23:in `load'
        from /usr/local/rvm/gems/ruby-2.3.1/bin/aws-session:23:in `<main>'
        from /usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

I expected the command to return with no error or output

I don't know the cause is, but if I log back out and in again it works. If I wait for a bit and do some other stuff it works again. Entering a subshell will not fix the error. I am using a fairly minimal install of ubuntu 16.04 with RVM and ruby-2.3.1

**Comment by zl4bv** [comment]
Hmm I've seen this too after switching from MRI ruby 2.2.x to 2.3.x.

**Comment by johndaviesco** [comment]
Sooo keen for this yo :+1:

**Comment by zl4bv** [comment]
@meringu @johndaviesco what version of rubygems are you running?

```
$ gem --version
```

This appears to be related to an upstream issue: https://github.com/rubygems/rubygems/issues/1420

**Comment by johndaviesco** [comment]
This is working for me now thanks @zl4bv :+1: :1st_place_medal: :100: :laughing:
